src/Entity/Extension.php
<?php
namespace App\Entity;

class Extension
{
    /** @var string */
    private $name;

    /** @var string|null */
    private $description;

    /** @var bool */
    private $micrusRepo;

    public function __construct(string $name, ?string $description = null, $micrusRepo = true)
    {
        $this->name = $name;
        $this->description = $description;
        $this->micrusRepo = $micrusRepo;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getDescription(): string
    {
        return $this->description ?? $this->name;
    }

    public function getRepo(): ?string
    {
        return sprintf('https://gitlab.com/Avris/%s%s', $this->micrusRepo ? 'Micrus-' : '', $this->name);
    }
}

src/Entity/Post.php
<?php
namespace App\Entity;

use Avris\Http\Request\UploadedFile;
use Avris\Forms\ChoiceHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table
 **/
class Post
{
    /**
     * @var string
     * @ORM\Id
     * @ORM\Column(type="string", length=36, options={"fixed" = true})
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $title = '';

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $content = '';

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @var string
     * @ORM\Column(type="string", length=7)
     */
    private $language = 'en';

    /**
     * @var float|null
     * @ORM\Column(type="float", nullable=true)
     */
    private $number;

    /**
     * @var integer|null
     * @ORM\Column(type="integer", nullable=true)
     */
    private $wholeNumber;

    /**
     * @var string|null
     * @ORM\Column(type="string", nullable=true)
     */
    private $url;

    /**
     * @var float|null
     * @ORM\Column(type="float", nullable=true)
     */
    private $percent;

    /**
     * @var float|null
     * @ORM\Column(type="float", nullable=true)
     */
    private $money;

    /**
     * @var string[]
     * @ORM\Column(type="json_array")
     */
    private $types = [];

    /**
     * @var string[]
     * @ORM\Column(type="json_array")
     */
    private $notes = [];

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User", inversedBy="posts")
     **/
    private $user;

    /**
     * @var Category[]|ArrayCollection
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="posts")
     * @ORM\JoinTable(name="category_post")
     **/
    private $categories;

    /**
     * @var UploadedFile
     */
    private $attachment;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $file;

    /**
     * @var Dependency[]|ArrayCollection
     * @ORM\OneToMany(targetEntity="Dependency", mappedBy="post", cascade={"persist", "remove"})
     */
    private $dependencies;

    /**
     * @var Dependency
     * @ORM\OneToOne(targetEntity="Dependency", cascade={"persist", "remove"})
     */
    private $mainDependency;

    public function __construct(User $user)
    {
        $this->categories = new ArrayCollection();
        $this->publishedAt = new \DateTime();
        $this->dependencies = new ArrayCollection();
        $this->mainDependency = new Dependency();
        $this->user = $user;
    }

    public function getIntro(): string
    {
        return mb_substr(strip_tags($this->content), 0, 300) . '...';
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): \DateTime
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTime $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getLanguage(): string
    {
        return $this->language;
    }

    public function getLanguageName(): string
    {
        return ChoiceHelper::LANGUAGES[$this->language];
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getNumber(): ?float
    {
        return $this->number;
    }

    public function setNumber($number): self
    {
        $this->number = $number ? (float) $number : null;

        return $this;
    }

    public function getWholeNumber(): ?int
    {
        return $this->wholeNumber;
    }

    public function setWholeNumber($wholeNumber): self
    {
        $this->wholeNumber = $wholeNumber ? (int) $wholeNumber : null;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getPercent(): ?float
    {
        return $this->percent;
    }

    public function setPercent($percent): self
    {
        $this->percent = $percent ? (float) $percent : null;

        return $this;
    }

    public function getMoney(): ?float
    {
        return $this->money;
    }

    public function setMoney($money): self
    {
        $this->money = $money ? (float) $money : null;

        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Category[]|ArrayCollection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    public function addCategories(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategories(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getTypes(): array
    {
        return $this->types;
    }

    public function setTypes(array $types): self
    {
        $this->types = $types;

        return $this;
    }

    public function getNotes(): array
    {
        return $this->notes;
    }

    public function setNotes(array $notes): self
    {
        $this->notes = array_values($notes);

        return $this;
    }

    public function getAttachment(): ?UploadedFile
    {
        return $this->attachment;
    }

    public function setAttachment(?UploadedFile $attachment): self
    {
        $this->attachment = $attachment;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    // TODO in controller
    public function handleFileUpload(string $rootDir): self
    {
        if ($this->attachment) {
            $this->file = $this->attachment->moveToRandom($rootDir . '/var/pics/', $this->file);
        }

        return $this;
    }

    /**
     * @return Dependency[]|ArrayCollection
     */
    public function getDependencies()
    {
        return $this->dependencies;
    }

    public function addDependencies(Dependency $dependency): self
    {
        $dependency->setPost($this);
        $this->dependencies->add($dependency);

        return $this;
    }

    public function removeDependencies(Dependency $dependency): self
    {
        $this->dependencies->removeElement($dependency);
        $dependency->setPost(null);

        return $this;
    }

    public function getMainDependency(): Dependency
    {
        return $this->mainDependency;
    }

    public function setMainDependency(Dependency $mainDependency): self
    {
        $this->mainDependency = $mainDependency;

        return $this;
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use App\Entity\Extension;
use App\Entity\Project;
use App\Form\FlashForm;
use App\Form\MailForm;
use App\Entity\User;
use App\Mail\TestTemplate;
use App\Service\FileDownloader;
use Avris\Micrus\Annotations\Annotation as M;
use Avris\Micrus\Controller\Controller;
use Avris\Http\Response\FileResponse;
use Avris\Http\Request\RequestInterface;
use Avris\Micrus\Mailer\Mail\Address;
use Avris\Micrus\Mailer\MailBuilder;
use Avris\Micrus\Mailer\Mailer;
use Avris\Micrus\Tool\FlashBag;

class HomeController extends Controller
{
    /**
     * @M\Route("/")
     */
    public function homeAction()
    {
        return $this->render([
            'projects' => [
                new Project('Dibsy'),
                new Project('Generator'),
                new Project('Avris Flags', 'https://flags.avris.it/', 'Flags-Home'),
                new Project('Avi'),
                new Project('Volatile'),
                new Project('Cropper'),
                new Project('Can I go home now', 'https://canigohome.avris.it/', 'GoHome'),
                new Project('QC', null, 'QC-Home'),
                new Project('Futurus', 'https://futurysci.avris.it/', 'Futurus-home'),
                new Project('Clavis'),
            ],
            'extensions' => [
                new Extension('Forms', null, false),
                new Extension('Localisator', null, false),
                new Extension('Twig', 'Twig module'),
                new Extension('Doctrine', 'Doctrine module'),
                new Extension('Mailer'),
                new Extension('Crud', 'CRUD generator'),
                new Extension('Imagine', 'Imagine module'),
                new Extension('Social', 'Social module'),
                new Extension('Annotations', 'Annotations module'),
                new Extension('GA', 'Google Analytics module'),
                new Extension('ReCaptcha', 'ReCaptcha widget'),
            ],
        ]);
    }

    /**
     * @M\Route("/hello/{uuid:id}", name="helloUser")
     */
    public function helloUserAction(User $user)
    {
        return $this->render([
            'name' => $user->getUsername(),
        ], 'Home/hello');
    }

    /**
     * @M\Route("/hello/{name=}", name="helloStranger")
     */
    public function helloStrangerAction($name = null)
    {
        return $this->render([
            'name' => $name ?: l('hello.stranger'),
        ], 'Home/hello');
    }

    /**
     * @M\Route("/extensions", name="extensions")
     */
    public function extensionsAction()
    {
        return $this->render();
    }

    /**
     * @M\Route("/flash", name="flash")
     */
    public function flashAction(RequestInterface $request)
    {
        $form = $this->form(FlashForm::class, null, $request);

        if ($data = $this->handleForm($form)) {
            $this->addFlash($data->type, $data->message);

            return $this->redirect($this->generateUrl('flash'));
        }

        return $this->render(['form' => $form]);
    }

    /**
     * @M\Route("/cookies", name="cookies")
     */
    public function cookiesAction(RequestInterface $request)
    {
        $count = $request->getCookies()->get('count', 0);

        $this->setCookie('count', $count + 1);

        return $this->render(['count' => $count]);
    }

    /**
     * @M\Route("/mail", name="mail")
     */
    public function mailAction(RequestInterface $request, MailBuilder $mailBuilder, Mailer $mailer)
    {
        $form = $this->form(MailForm::class, null, $request);
        $data = $this->handleForm($form);

        if (!$data) {
            return $this->render([
                'form' => $form,
            ]);
        }

        $mail = $mailBuilder->build(
            $this->get(TestTemplate::class),
            $data->locale,
            [
                'user' => 'Anonymous User',
                'foo' => 'bar',
            ]
        );
        $mail->addTo(new Address($data->email));

        if ($request->getData()->has('send')) {
            $result = $mailer->spool($mail);

            $this->addFlash(
                $result ? FlashBag::SUCCESS : FlashBag::DANGER,
                l(
                    'email.' . ($result ? 'spooled' : 'failed'),
                    ['email' => $data->email]
                ),
                false
            );
        }

        return $this->render([
            'form' => $form,
            'mail' => $mail,
        ]);
    }

    /**
     * Demonstration of JSON responses and of retrieving services that are created in factory mode
     *
     * @M\Route("/factory", name="factory")
     */
    public function factoryAction()
    {
        return $this->renderJson([
            1 => $this->get('countedProduct')->getValue(),        //should be 1
            2 => $this->get('countedProduct')->getValue(),        //should be 1
            3 => $this->get('countedProduct')->getValue(),        //should be 1
            4 => $this->get('countedProductFactory')->getValue(), //should be 2
            5 => $this->get('countedProductFactory')->getValue(), //should be 3
            6 => $this->get('countedProductFactory')->getValue(), //should be 4
            7 => $this->get('countedProduct')->getValue(),        //should be 1
            8 => $this->get('countedProduct')->getValue(),        //should be 1
            9 => $this->get('countedProduct')->getValue(),        //should be 1
        ]);
    }

    /**
     * @M\Route("/files", name="files")
     */
    public function filesAction()
    {
        return $this->render();
    }

    /**
     * @M\Route("/files/logo/{download=}", name="filesLogo")
     */
    public function filesLogoAction($download = false)
    {
        return new FileResponse($this->getProjectDir() . '/assets/images/logo.png', (bool) $download);
    }

    /**
     * @M\Route("/files/fetch", name="filesFetch")
     */
    public function filesLogoDownloadAction(FileDownloader $downloader)
    {
        $file = $downloader->download(
            'https://www.google.de/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
        );

        return new FileResponse($file->getTmpName());
    }
}

templates/Home/cookies.html.twig
{% extends 'layout' %}

{% block content %}
    <h3>{{ 'cookies.header'|l }}</h3>
    <p>
        {{ 'cookies.count'|l }}:
        <strong class="cookie-count">{{ count }}</strong>
    </p>
{% endblock %}

templates/Home/extensions.html.twig
{% extends 'layout' %}

{% block content %}
    <p>{{ 'now'|date('format.datetime'|l) }}</p>
    <p>{{ 'test twig extension'|wave }}</p>
    <hr/>
    {% for i in 0..5 %}
        <p>{{ 'extensions.counting'|l({foo: 'bar', count: i}) }}</p>
    {% endfor %}
    <p>{{ 'extensions.nested'|l({entry: 'gay'}) }}</p>
    <p>{{ 'entity:Foo.singular'|l }}</p>
    <p>{{ 'extensions.nonexistent'|l }}</p>
    <hr/>
    {{ dump(app) }}
{% endblock %}

templates/Home/files.html.twig
{% extends 'layout' %}

{% block content %}
    <h3>{{ 'files.header'|l }}</h3>
    <ul>
        <li>
            <a href="{{ route('filesLogo') }}">
                {{ 'files.openLogo'|l }}
            </a>
        </li>
        <li>
            <a href="{{ route('filesLogo', {download: true}) }}">
                {{ 'files.downloadLogo'|l }}
            </a>
        </li>
        <li>
            <a href="{{ route('filesFetch') }}">
                {{ 'files.fetch'|l }}
            </a>
        </li>
    </ul>
{% endblock %}

templates/Home/flash.html.twig
{% extends 'layout' %}

{% block content %}
    <form method="post" class="form-inline">
        {{ widget(form, form.name, 'Avris\\Forms\\Style\\BootstrapInline') }}
        <button class="btn btn-primary">{{ 'form.ok'|l }}</button>
    </form>
{% endblock %}

templates/Home/hello.html.twig
{% extends 'layout' %}

{% block content %}
    <p class="bold">{{ 'hello.hello'|l({'name': name}) }}</p>
{% endblock %}

templates/Home/home.html.twig
{% extends 'layout' %}

{% block jumbotron %}
    {% include 'Home/jumbotron' %}
{% endblock %}

{% block content %}
    <section id="features">
        <h2><span class="fas fa-cogs"></span> {{ 'home.features.header'|l }}</h2>
        <hr/>
        <ul>
            <li>{{ 'home.features.oop'|l }}</li>
            <li>{{ 'home.features.mvc'|l }}</li>
            <li>{{ 'home.features.modules'|l }}</li>
            <li>{{ 'home.features.container'|l }} <small>{{ 'home.features.containerPsr'|l }}</small></li>
            <li>{{ 'home.features.autowiring'|l }}</li>
            <li>{{ 'home.features.dispatcher'|l }}</li>
            <li>{{ 'home.features.orm'|l }} <small>{{ 'home.features.ormSupport'|l({doctrine: '<a href="http://www.doctrine-project.org/projects/orm.html"  target="_blank" rel="noopener">Doctrine</a>'}) }}</small></li>
            <li>{{ 'home.features.routing'|l }}</li>
            <li><a href="https://gitlab.com/Avris/Micrus-Crud" target="_blank" rel="noopener">{{ 'home.features.crud'|l }}</a></li>
            <li>{{ 'home.features.templating'|l }} <small>{{ 'home.features.templatingSupport'|l({twig: '<a href="http://twig.sensiolabs.org/" target="_blank" rel="noopener">Twig</a>'}) }}</small></li>
            <li>{{ 'home.features.auth'|l }}</li>
            <li>{{ 'home.features.config'|l({yaml: '<a href="http://yaml.org/" target="_blank" rel="noopener">YAML</a>'}) }}</li>
            <li>{{ 'home.features.cli'|l }} <small>{{ 'home.features.cliTool'|l({sfConsole: '<a href="http://symfony.com/doc/current/components/console/introduction.html" target="_blank" rel="noopener">Symfony Console</a>'}) }}</small></li>
            <li>{{ 'home.features.formsElegant'|l }} <a href="https://gitlab.com/Avris/Forms" target="_blank" rel="noopener">{{ 'home.features.forms'|l }}</a></li>
            <li><a href="https://gitlab.com/Avris/Localizator" target="_blank" rel="noopener">{{ 'home.features.localisation'|l }}</a></li>
            <li>{{ 'home.features.logger'|l({monolog: '<a href="https://github.com/Seldaek/monolog" target="_blank" rel="noopener">Monolog</a>'}) }} <small>{{ 'home.features.loggerPsr'|l }}</small></li>
            <li>{{ 'home.features.cache'|l }} <small>{{ 'home.features.cachePsr'|l }}</small></li>
            <li>{{ 'home.features.flash'|l }}</li>
        </ul>
    </section>
    <section id="checkOut">
        <div class="row mt-5 mb-5">
            <div class="col-lg-6 text-center">
                <h3><span class="fas fa-cogs fa-fw"></span> {{ 'home.checkOut.demo'|l }}</h3>
                <div>
                    <span class="fab fa-gitlab fa-fw"></span>
                    <a href="https://gitlab.com/Avris/Micrus-Demo" target="_blank" rel="noopener">
                        gitlab.com/Avris/Micrus-Demo
                    </a>
                </div>
            </div>
            <div class="col-lg-6 text-center">
                <h3><span class="fas fa-book fa-fw"></span> {{ 'home.checkOut.docs'|l }}</h3>
                <div>
                    <span class="fas fa-external-link-alt fa-fw"></span>
                    <a href="https://docs.avris.it/micrus" target="_blank" rel="noopener">
                        docs.avris.it/micrus
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section id="projects">
        <h2><span class="fas fa-tv"></span> {{ 'home.projects.header'|l }}</h2>
        <table class="table">
            {% for project in projects %}
                <tr>
                    <th>
                        <img src="{{ asset('images/' ~ project.name ~ '.png') }}">
                        <h3 class="h4">
                            {{ project.name }}
                        </h3>
                        <p>
                            {{ ('home.projects.' ~ project.name)|l }}
                        </p>
                    </th>
                    <td>
                        <a href="{{ project.website }}" target="_blank" rel="noopener">
                            <span class="fas fa-globe"></span>
                            {{ project.website|clearUrl }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ project.repo }}" target="_blank" rel="noopener">
                            <span class="fab fa-gitlab"></span>
                            {{ project.repo|clearUrl }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </section>

    <section id="extensions">
        <h2><span class="fas fa-plug"></span> {{ 'home.extensions.header'|l }}</h2>
        <table class="table">
            {% for extension in extensions %}
                <tr>
                    <th>
                        <h3 class="h4">
                            {{ extension.description }}
                        </h3>
                        <p>
                            {{ ('home.extensions.' ~ extension.name)|l }}
                        </p>
                    </th>
                    <td>
                        <a href="{{ extension.repo }}" target="_blank" rel="noopener">
                            <span class="fab fa-gitlab"></span>
                            {{ extension.repo|clearUrl }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </section>
{% endblock %}

templates/Home/jumbotron.html.twig
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-lg-3 mx-sm-auto d-none d-lg-block text-center align-self-center">
                <img src="{{ asset('images/logoText.svg') }}" alt="{{ 'main.title'|l }}"/>
                <h1 class="text-center">{{ 'main.title'|l }}</h1>
            </div>
            <div class="col-xs-12 col-lg-4 mx-sm-auto align-self-center">
                <p class="h2 text-center">{{ 'main.slogan'|l }}</p>
                <p class="text-justify">{{ 'main.intro.0'|l }}</p>
                <p class="text-justify">{{ 'main.intro.1'|l }}</p>
            </div>
        </div>
    </div>
</div>

templates/Home/mail.html.twig
{% extends 'layout' %}

{% block content %}
    <form method="post" class="form">
        {{ widget(form, form.name, 'Avris\\Forms\\Style\\Bootstrap2') }}
        <div class="text-right">
            <div class="btn-group">
                <button name="preview" class="btn btn-default">
                    <span class="fas fa-tv"></span>
                    {{ 'email.preview'|l }}
                </button>
                <button name="send" class="btn btn-primary">
                    <span class="fas fa-paper-plane"></span>
                    {{ 'email.send'|l }}
                </button>
            </div>
        </div>
    </form>
    <div>
        {% if mail is defined %}
            <hr class="mail-separator"/>
            {{ mail|raw }}
        {% endif %}
    </div>
{% endblock %}